### ISSUE TITLE
“misc” isn’t a valid CSL item type

### ISSUE THREAD

**Issue by njbart** [inukshuk/anystyle#110]
In anystyle’s CSL JSON export format, I encountered `"type":"misc"`. However, `misc` isn’t a valid CSL item type, and pandoc-citeproc chokes on it. 

The valid CSL item types are listed here: http://docs.citationstyles.org/en/1.0.1/specification.html#appendix-iii-types.

Since there is no CSL type at all that closely resembles `misc`, I’d go for `article`.

(pandoc citeproc itself uses `no-type` when converting from bibtex, but that’s neither an official CSL type, nor could I find out whether citeproc-js uses it, too, so I’m not sure whether this could be recommended for anystyle.)

**Comment by inukshuk** [comment]
Thanks for reporting! I'm going to close this because this is already 'fixed' in version 1.0; if no type can be inferred the type field will not be added.
