### ISSUE TITLE
Mismatch between text and regex encoding when extracting from PDF

### ISSUE THREAD

**Issue by a-fent** [inukshuk/anystyle#111]
When trying to parse text from a PDF for a Finder, an exception will be raised by StringUtils::display_chars because the regex there is UTF-8 but the text from the PDF is in Windows-Latin encoding (this is Windows...).

The fix is to explicitly tell pdftotext to extract UTF-8 encoded text:
```

modified   lib/anystyle/utils.rb
@@ -57,7 +57,7 @@ module AnyStyle
     module_function
 
     def pdf_to_text(path, layout: true)
-      %x{pdftotext #{layout ? ' -layout' : ''} -eol unix -q "#{path}" -}
+      %x{pdftotext #{layout ? ' -layout' : ''} -eol unix -enc utf8 -q "#{path}" -}
     end
 
     def pdf_info(path)

```

**Comment by inukshuk** [comment]
Thanks!

**Comment by a-fent** [comment]
Hi - sorry to reopen this, but my original fix was incorrect, but being masked by -q argument to pdftotext. The following does actually get some text out for labelling:

modified   lib/anystyle/utils.rb
@@ -57,7 +57,9 @@ module AnyStyle
     module_function
```
 
     def pdf_to_text(path, layout: true)
-      %x{pdftotext #{layout ? ' -layout' : ''} -eol unix -q "#{path}" -}
+      txt = %x{pdftotext #{layout ? ' -layout' : ''} -eol unix -enc UTF-8 -q "#{path}" -}
+      raise "PDF to text did not run correctly, error code #{$?}" if $? != 0
+      txt.force_encoding('UTF-8')
     end
 
     def pdf_info(path)
```
