### ISSUE TITLE
Remove 'DOI:' prefix form DOIs in extracted metadata

### ISSUE THREAD

**Issue by coryschires** [inukshuk/anystyle#113]
## Problem
When AnyStyle extracts DOIs they often (always?) include a "doi:" prefix. As far as I can tell (and you're certainly more expert than I am), citeproc does not deal well with these prefixes. For example, when passing the metadata to citeproc-js, I see odd / undesirable formatting such as:

    https://doi.org/doi:10.1.1.130.8504 # Broken link due to `doi:`
    doi:doi:10.1.1.130.8504             # Notice redundant 'doi:' prefix

## How to recreate

    raw_citation = %{Kessler, R.C. 1998. "Methodological Studies of the Composite International Diagnostic Interview" International Journal of Methods in Psychiatric Research 7 (1): 33-55. doi:10.1002/mpr.33.}

    metadata = AnyStyle.parse(raw_citation, format: :csl).first
    # => {
      :author => [{ :family => "Kessler", :given => "R.C." }],
      :date => "1998",
      :title => "Methodological Studies of the Composite International Diagnostic Interview",
      :volume => "7",
      :type => "article-journal",
      :"container-title" => "International Journal of Methods in Psychiatric Research",
      :issue => "1",
      :page => "33–55",
      :DOI => "doi:10.1002/mpr.33."
    }

## Desired behavior
Assuming I understand the CSL-JSON spec correctly, any `DOI:` prefix should be removed (case insensitive).

**Comment by coryschires** [comment]
Meant to mention... If helpful CrossRef provides a solid regex in this blog post:
https://www.crossref.org/blog/dois-and-matching-regular-expressions

**Comment by inukshuk** [comment]
That's cool. I added the first two patterns to the [DOI normalizer](https://github.com/inukshuk/anystyle/blob/964f89697c4e97257908504e3e6c8c7b305361ab/lib/anystyle/normalizer/locator.rb#L15); normalizers are relatively trivial post-processing we use to clean-up values.
