### ISSUE TITLE
DOI formatted as URL

### ISSUE THREAD

**Issue by bwiernik** [inukshuk/anystyle#116]
When a DOI is formatted as a URL:
`http://dx.doi.org/10.1234/567890`
`https://dx.doi.org/10.1234/567890`
`http://doi.org/10.1234/567890`
`https://doi.org/10.1234/567890`
It gets parsed as a URL, rather than as a DOI. It would be better if the URL matches the regex `/.*doi\.org.*/` for it to be parsed as a DOI then normalized.

On a related note, the DOI normalizer won't match shortDOIs, which have the form:
`10/abcde`
Rather than `/10\.(\d{4,9}\/[-._;()\/:A-Z0-9]+|1002\/\S+)/`, the regex `/10\/[^\s]*[^\s\.,]/` will recognize both regular DOI and shortDOI names.

**Comment by inukshuk** [comment]
I was a bit puzzled what to do about DOI URLs as well. I *think* it is better to train them as URLs consistently to make the URL and DOI labels easier to distinguish and then use the normalizer to extract DOIs from URLs. That's what you suggest, too, right?

That said, this seems to be working for me. Using your examples:

```
$ anystyle --version
anystyle version 1.3.1 (cli 1.2.0, data 1.2.0)

$ anystyle --stdout -f csl parse <(echo "http://dx.doi.org/10.1234/567890")
[
  {
    "type": null,
    "URL": "http://dx.doi.org/10.1234/567890",
    "DOI": "10.1234/567890"
  }
]

$ anystyle --stdout -f csl parse <(echo "https://dx.doi.org/10.1234/567890")
[
  {
    "type": null,
    "URL": "https://dx.doi.org/10.1234/567890",
    "DOI": "10.1234/567890"
  }
]
```

About short DOIs, could you give me a few [examples like these](https://github.com/inukshuk/anystyle/blob/master/spec/anystyle/normalizer/locator_spec.rb#L8)? I'll be happy to adjust the normalizer's pattern, but a few more tests would be great.

Thanks for reporting!

**Comment by bwiernik** [comment]
Doing both URL and DOI would be fine, I think. But I think you should only normalize out DOIs from URLs that have one of the four patterns given above. Several sites (JSTOR worst of all) use DOI-like patterns in their URLs that are not valid DOIs. The URLs that might have valid DOIs with different domains (e.g., https://doai.io/, https://sci-hub.*/) are rare enough that I think you can ignore them. Several publishers do include the DOI in their URL scheme, but I worry that pulling them out would catch too many fake DOIs. I think false positives are worse than false negatives/less convenience here. 

Right now, when I am parsing items using the anystyle.io web app, URL-formatted DOIs only get picked up by the URL field. 

I’ll give you some examples.

**Comment by inukshuk** [comment]
Ah, that explains it! anystyle.io still runs on anystyle 0.x which is very far behind the CLI / Ruby version unfortunately.

I absolutely agree about the false positives. So you're suggesting to try to extract DOIs from URLs only for `.doi.org` domains? Let's do that!

**Comment by bwiernik** [comment]
Some example short DOIs are 
`10/aabbe`
`10/gckfx5`
`10/abc`

They all take the form `10/` followed by a string of (I believe a minimum of 3) alphanumeric characters.
