### ISSUE TITLE
unicode support in anystyle cli

### ISSUE THREAD

**Issue by sathishvelu1984** [inukshuk/anystyle#122]
The below mentioned command i use to parse the bibliography

`>>ruby.exe anystyle -f json,xml parse biblio.txt  > bib.xml`

biblio.txt file contains the text mentioned below

`Stephen F. 1978. Introducción a la Teoría de la Estadística. Spain: Aguilar. (Original in english, 1992).
`
when i parse the file json content has correct unicode for ó and í, but the xml file has junk(Ã³, Ã) characters in it, how to resolve this issue

Thanks & Regards

**Comment by inukshuk** [comment]
Does the XML file [set the encoding at the top](https://github.com/inukshuk/anystyle/blob/master/res/parser/core.xml#L1)?

Does this happen if you do not pipe the contents, e.g. just run `anystyle -f json,xml parse biblio.txt` and check the `biblio.xml` file.

Finally, if the biblio.xml has the right encoding at the top but the characters are wrong, could you post the file here?

**Comment by sathishvelu1984** [comment]
> 
> 
> Does the XML file [set the encoding at the top](https://github.com/inukshuk/anystyle/blob/master/res/parser/core.xml#L1)?
> 
> Does this happen if you do not pipe the contents, e.g. just run `anystyle -f json,xml parse biblio.txt` and check the `biblio.xml` file.
> 
> Finally, if the biblio.xml has the right encoding at the top but the characters are wrong, could you post the file here?
Sorry, my mistake, it's working fine :-p,
