### ISSUE TITLE
Can't get non-csl format with ruby script

### ISSUE THREAD

**Issue by Jmuccigr** [inukshuk/anystyle#125]
Great service and website. I thought I would use the ruby functionality to create some local services on my laptop, but I'm having trouble getting anything other than csl output. I'm using the plain script from the readme:

```ruby
require 'anystyle'

pp AnyStyle.parse('Derrida, J. (1967). L’écriture et la différence (1 éd.). Paris: Éditions du Seuil.', format: :csl)
```

This works fine, but if I want some other format, it won't work. Using "json" or "tex" in place of "csl" gives an error:

```
rb:190:in `parse': format not supported: json (ArgumentError)
	from /Users/john_muccigrosso/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/anystyle-1.3.3/lib/anystyle.rb:65:in `parse'
	from /Users/john_muccigrosso/Downloads/BBEditRunTemp-anystyle.rb:3:in `<main>'
```

When I use "bibtex", I get this unhelpful output:

```
#<BibTeX::Bibliography data=[1]>
```

I'm definitely not a big ruby user, so this may be something stupid on my part. Any help appreciated.

**Comment by inukshuk** [comment]
You can use `:hash` to return a Ruby Hash (this is also the default) which is similar to JSON (can also be serialized as JSON using its `to_json` method).

When you use `:bibtex` you get a `BibTeX::Bibliography` object. You can do a lot of things with it (check out the [documentation](https://github.com/inukshuk/bibtex-ruby) if you're interested) -- to get the BibTeX as a 'string' you would call the `to_s` method on it.

If you're not familiar with Ruby, you might be interested in using [anystyle-cli](https://github.com/inukshuk/anystyle-cli) instead.

**Comment by Jmuccigr** [comment]
Thanks. That helps. Ok with a PR to add this to the readme?

The cli requires a file, if I understand correctly, and I’m looking to incorporate this into a OSX service that will act on highlighted text.

**Comment by inukshuk** [comment]
Yes, you're absolutely right, the cli currently requires a file. Reading the input directly from the CLI is something we should definitely add. We already  have a [PR](https://github.com/inukshuk/anystyle-cli/pull/9) to add single references that might be useful, but I'd prefer a new switch to parse from stdin instead of an extra command. (We'll add this eventually!)

PRs are always welcome!
