### ISSUE TITLE
ampersand causes author parsing problem

### ISSUE THREAD

**Issue by sckott** [inukshuk/anystyle#126]
the file [stuff.txt](https://github.com/inukshuk/anystyle/files/3672352/stuff.txt)

with 

> Petersen, A. H., & Ekstrøm, C. T. (2019). dataMaid: Your Assistant for Documenting Supervised Data Quality Screening in R. Journal of Statistical Software, 90(6). <https://doi.org/10.18637/jss.v090.i06>

```
anystyle --stdout -f csl parse stuff.txt
```

gives

```
[
  {
    "author": [
      {
        "literal": "Petersen, A. H., & Ekstrøm, C. T."
      }
    ],
    "title": "dataMaid: Your Assistant for Documenting Supervised Data Quality Screening in R",
    "volume": "90",
    "type": "article-journal",
    "container-title": "Journal of Statistical Software",
    "issue": "6",
    "issued": "2019",
    "URL": "https://doi.org/10.18637/jss.v090.i06",
    "DOI": "10.18637/jss.v090.i06"
  }
]
```

Tried removing the ampersand and then the authors were parsed. Any way to have the authors still be parsed if there's an ampersand in the author names string?

**Comment by inukshuk** [comment]
A quick fix would be to re-configure the name normalizer. I don't think the CLI tool currently exposes that functionality, but it would be an easy hack until it does.

Here's just one idea:

    $ irb
    >> require 'anystyle'
    >> AnyStyle.parser.normalizers[15].namae.options[:separator]
    => prints the current separator pattern

Now adjust the pattern like this:

    >> AnyStyle.parser.normalizers[15].namae.options[:separator] = /\A(and|AND|(, )?&|;|und|UND|y|e)\s+/

And then when you parse your reference:
```
>> pp AnyStyle.parse 'Petersen, A. H., & Ekstrøm, C. T. (2019). dataMaid: Your Assistant for Documenting Supervised Data Quality Screening in R. Journal of Statistical Software, 90(6). https://doi.org/10.18637/jss.v090.i06', format: 'csl'
[{:author=>
   [{:family=>"Petersen", :given=>"A.H."},
    {:family=>"Ekstrøm", :given=>"C.T."}],
  :title=>
   "dataMaid: Your Assistant for Documenting Supervised Data Quality Screening in R",
  :volume=>"90",
  :type=>"article-journal",
  :"container-title"=>"Journal of Statistical Software",
  :issue=>"6",
  :issued=>"2019",
  :URL=>"https://doi.org/10.18637/jss.v090.i06",
  :DOI=>"10.18637/jss.v090.i06"}]
```

To patch the CLI tool, you could just add that one line from above in the pre section (starting at line 64) of `bin/anystyle` in the anystyle-cli gem. Where it is depends on how you installed it, but if you check `gem env` and look at 'GEM PATHS' that should point you to it. For example, I have it installed at `.gem/ruby/2.6.4/gems/anystyle-cli-1.2.0/bin/anystyle`.

To improve the name parsing for good, we could consider adding this by default, but we'd have to test for adverse effects first.

**Comment by sckott** [comment]
thx for a quick response. I'll try calling anystyle from Ruby and adjusting the pattern as you demonstrated, and see if that works as a first run at it. I'll let you know

**Comment by sckott** [comment]
adjusting the separator works for me, thanks for the help
