### ISSUE TITLE
Page range interpreted as publisher

### ISSUE THREAD

**Issue by Jmuccigr** [inukshuk/anystyle#131]
Here's a citation in which the page range gets read as publisher:

```
COARELLI F., 1976, "Cinque frammenti di una tomba dipinta dall'Esquilino (Arieti)," in Affreschi romani dalle raccolte dell'Antiquarium comunale, Roma: 22-28
```

Here's the output:

```
[
  {
    "author": [
      {
        "family": "COARELLI",
        "given": "F."
      }
    ],
    "date": [
      "1976"
    ],
    "title": [
      "Cinque frammenti di una tomba dipinta dall'Esquilino (Arieti)\""
    ],
    "container-title": [
      "Affreschi romani dalle raccolte dell'Antiquarium comunale"
    ],
    "location": [
      "Roma"
    ],
    "publisher": [
      "22-28"
    ],
    "type": "chapter"
  }
]
```

I don't know the code well enough to figure out where this is happening, and I get why something after a colon would be read as publisher, but it seems like any time there's a number range like this outside the title, it's very likely the page range and not something else.

That is, anything like this (again, outside the title), is likely the page range:
```
[0-9]+\s*[-–—]\s*[0-9]+
```

Perhaps an exception could be made for things that look like year ranges.

**Comment by inukshuk** [comment]
We already have a suitable [feature pattern](https://github.com/inukshuk/anystyle/blob/master/lib/anystyle/feature/number.rb#L23) to detect this page range, so this is just a matter of adding some examples to our [training data](https://github.com/inukshuk/anystyle/blob/master/res/parser/core.xml) and rebuild the default model. (You can obviously train only your local model, but this is definitely something we can add to the default.)

**Comment by Jmuccigr** [comment]
Happy to help.

**Comment by inukshuk** [comment]
If you could add 2-5 references to the [core.xml](https://github.com/inukshuk/anystyle/blob/master/res/parser/core.xml), I'll re-train the model and push a new version to RubyGems.

**Comment by Jmuccigr** [comment]
OK, I added two from the journal that I found the original one in. One is a book section and the other a journal article. Hope I did it right!

**Comment by inukshuk** [comment]
Pushed 1.3.6 to RubyGems. Please let me know if you still run into location + publisher results for location + page-range (in that case we'll need more training data; but checking a few references from FOLD&R looked promising to me).

**Comment by Jmuccigr** [comment]
Sounds good. As soon as 1.3.6 shows up in my `gem update`, I'll check it out.

**Comment by inukshuk** [comment]
Oops, thanks for the poke -- I did not push the Gem after all. Should be there now!

**Comment by Jmuccigr** [comment]
And it works!
