### ISSUE TITLE
error: undefined method `[]' for #<Wapiti::NativeError:0x000000000187dab0>

### ISSUE THREAD

**Issue by dominic01** [inukshuk/anystyle#138]
Ruby ver 2.6.3
Installed Anystyle gem

Just run " anystyle -P x.mod check ./res/parser/gold.xml"

Got the error:
Checking gold.xml.................error: undefined method `[]' for #<Wapiti::NativeError:0x000000000187dab0>

**Comment by inukshuk** [comment]
Can you reproduce this with the default model?

This is probably because your model does not contain some of the labels used `gold.xml` -- checking labels which the model does not know exist will cause an error, probably that's what is causing this (sorry for cryptic error message!).
