### ISSUE TITLE
Extracting tag probabilities?

### ISSUE THREAD

**Issue by tylerascott** [inukshuk/anystyle#141]
Hello,
   I am curious about the feasibility of extracting the individual probabilities assigned to specific reference parts. I'm working with many non-traditional references, and so would like to be able to sort in terms of confidence associated with the title vs. author vs. imprint, that sort of thing. Is possible within the current program?

**Comment by inukshuk** [comment]
Yes, that's possible. You need to pass enable the `score` parameter passed to the model's label method. IIRC all options passed to AnyStyle's parse method should be pushed down to the label. The scores are preserved only in the wapiti/dataset output format: they are assigned to each 'token' -- in the case of AnyStyle's model that is a single word.

For some related documentation [see here](https://github.com/inukshuk/wapiti-ruby#labelling).
