### ISSUE TITLE
Separating vol/issue/pages

### ISSUE THREAD

**Issue by md9692** [inukshuk/anystyle#150]
Hi, 

I have a vast bibliography I'd love to convert to a BibTeX, all in this format:

Bbosa N, Kaleebu P, Ssemwanga D. HIV subtype diversity worldwide. _Curr Opin HIV AIDS_. 2019;14(3):153-60.

The problem is with the date onwards, which anystyle thinks is a vol/issue but is actually a date;vol(issue):pages-pages

Since this is such standard notation, I'm wondering if others have had this problem?

**Comment by inukshuk** [comment]
Should be fixed in 1.3.12.

**Comment by md9692** [comment]
Not seeing it fixed in 1.3.12 
<img width="1216" alt="Screenshot 2020-08-19 at 15 22 34" src="https://user-images.githubusercontent.com/57666469/90647092-dbf79e80-e22f-11ea-9cdb-67b480078bcf.png">

**Comment by inukshuk** [comment]
No this is as expected. In the first step, the sentence is split into words. We experimenting with more complex separator patterns than white space for latin script based text, but it was actually counterproductive and made it much harder to re-construct the original input. For this reason there's only one label we can apply to '2019;14(3):153-60.' as a whole -- the label is called 'Volume / Issue' for simplicity (adding separate labels for all the volume, issue, date, page number combinations would not be helpful.

Anyway, if you click through to a format other than XML, you should see that all of volume, issue, date and page number got parsed. Here is the CSL-JSON for your example:

![Screenshot from 2020-08-19 18-53-09](https://user-images.githubusercontent.com/325102/90666226-5f73b880-e24d-11ea-9d3c-351538d7f368.png)

The BibTeX format uses CSL-JSON as an intermediary step so it should work there as well.

**Comment by md9692** [comment]
Oh yes you're right! Thank you so much!
