### ISSUE TITLE
biblatex article journaltitle

### ISSUE THREAD

**Issue by leezu** [inukshuk/anystyle#155]
As per https://mirrors.concertpass.com/tex-archive/macros/latex/contrib/biblatex/doc/biblatex.pdf#021100%3Aarticle.4, anystyle should provide `journaltitle = {}` instead of `journal = {}` for articles?

**Comment by inukshuk** [comment]
Hmm, I believe this has come up before. As far as I remember, only BibLaTeX uses `journaltitle` while most other tools use `journal`. BibLaTeX automatically converted `journal` fields, though, if I'm not mistaken: is that no longer the case?

**Comment by inukshuk** [comment]
It's listed as an alias on page 32 of the documentation.

**Comment by leezu** [comment]
Thank you for checking the documentation. It seems like emacs doesn't handle the biblatex aliases correctly. I opened a bug report with emacs: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44976
