### ISSUE TITLE
Issue with BibTeX author field when a name contains two consecutive accented characters.

### ISSUE THREAD

**Issue by myshevchuk** [inukshuk/anystyle#156]
Hi! I've run across a peculiar issue with `anystyle -f bib parse reference.txt` outputting an empty author field:

```bibtex
@article{ak2017a,
  author = {},
  date = {2017},
  title = {Gamifying an ICT course: Influences on engagement and academic performance},
  volume = {69},
  pages = {98–107},
  journal = {Computers in Human Behavior}
}
```

Contents of `reference.txt`:

```txt
Çakıroğlu, Ü., Başıbüyük, B., Güler, M., Atabay, M., & Yılmaz Memiş, B. (2017). Gamifying an ICT course: Influences on engagement and academic performance. Computers in Human Behavior, 69, 98–107.
```

The field is only empty when a name contains two accented (non-ASCII) characters one after another. In the above example it is the name `Başıbüyük` with the characters `ş` and `ı` causing the issue. It doesn't matter what the characters are, so this name will also lead to an empty author field: `Baüöbüyük`. With three or more accented characters in a row, e.g. `Baüöäbüyük`, the problem disappears and the author field has the expected value.

Title and journal fields are unaffected. Other output formats such as XML or JSON are unaffected.

I'm experiencing this issue with AnyStyle CLI, but I had a feeling it's related to core AnyStyle.

> anystyle version 1.3.13 (cli 1.3.1, data 1.2.0)
> ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

**Comment by inukshuk** [comment]
Good find! You should be able to fix this by updating the `namae` Gem to version 1.0.2. It turns out that we were using `StringScanner#peek` which for some checks, which always returns the requested number of bytes, not characters, so this failed for all names where the first 8 byte did not happen to be valid unicode sequences.

**Comment by myshevchuk** [comment]
Great, thanks a lot!
