### ISSUE TITLE
Duplicates in core.xml

### ISSUE THREAD

**Issue by silviaegt** [inukshuk/anystyle#165]
While I was playing around searching for the [language distribution](https://github.com/inukshuk/anystyle/issues/163) in [core.xml](https://github.com/inukshuk/anystyle/blob/master/res/parser/core.xml) I found these eight duplicated `<titles>`:

"Sincerity and Objectification." (see: [1](https://github.com/inukshuk/anystyle/blob/master/res/parser/core.xml#L4821) | [2](https://github.com/inukshuk/anystyle/blob/master/res/parser/core.xml#L5244) )	
“The Concentration City.” (see: [1 ](https://github.com/inukshuk/anystyle/blob/master/res/parser/core.xml#L5322)| [2](https://github.com/inukshuk/anystyle/blob/master/res/parser/core.xml#L5887)) 
B. F. Skinner: A fresh appraisal
CIA World Factbook.
Indirect relevance and bias in inductive concept learning.
Planning for conjunctive goals.
Robin Hood: a collection of all the ancient poems, songs, and bal- lads (sic), now extant, relative to that celebrated English outlaw.
Threat-removal strategies for partial-order planning.

Perhaps they were intended to be twice, in which case I would love to learn why? -- if not, hope this report is useful 👍

**Comment by inukshuk** [comment]
Good catch, thanks!

The duplicates are surely there by accident. We actually wrote some tools to make it easier to detect those, but it seems that we missed at least three duplicates: at least `Wapiti::Dataset.open('core.xml').uniq` finds three, I need to check the others by hand -- it's possible that there are duplicate references which are tagged slightly differently which can't be good!

**Comment by inukshuk** [comment]
After a quick review there were three duplicates and bad reference (a duplicate that contained parts of another reference at the end). The others are all duplicate references using different citation styles so they serve a purpose and can stay. Thanks for reporting!
