### ISSUE TITLE
Parse an extra dot at the end of DOI

### ISSUE THREAD

**Issue by atxy-blip** [inukshuk/anystyle#169]
Under some citation styles, the dot symbol is used as a separator, and anystyle fails to ignore it. For example, in the following citation:

> Lei, Suo, Liu (2021): Lei, Y.; Suo, B.; Liu, W. ICAS: Imposed Automatic Selection and Localization of Complete Active Spaces. J. Chem. Theory Comput. 2021, acs.jctc.1c00456. https://doi.org/10.1021/acs.jctc.1c00456.

Anystyle tends to identify the doi as follows. Notify the dot at the end.

>  https://doi.org/10.1021/acs.jctc.1c00456.

Thanks for your powerful tool anyway.

**Comment by inukshuk** [comment]
Thanks! This should be easy to address in the [locator normalizer](https://github.com/inukshuk/anystyle/blob/master/lib/anystyle/normalizer/locator.rb).
