### ISSUE TITLE
Question: Struggling to understand how to use `AnyStyle::Format::BibTeX`

### ISSUE THREAD

**Issue by SkepticMystic** [inukshuk/anystyle#173]
Hello!
Thank you for this very useful tool.
I am brand new to Ruby, so I am having some trouble understanding how to use your API..
I want to format the `parse` output as `bibtext`, so I'm trying to use this command, and other combinations. Can you help me understand how to use the `format_bibtex` file?

```ruby
require "anystyle"

output = AnyStyle.parse """
Turing, Alan, Computing Machinery and Intelligence, Mind 59, pp 433-460 (1950)
"""

bib = AnyStyle.format.bibtext.format_bibtex(output)

File.write('bib.txt', bib)
```

**Comment by inukshuk** [comment]
You can use the `format` option on the `parse` method to get the parse results in the desired format.

```Ruby
require "anystyle"

input = """
Turing, Alan, Computing Machinery and Intelligence, Mind 59, pp 433-460 (1950)
"""

# This gives you a BibTeX::Bibliography object. You can print it out using .to_s
bib = AnyStyle.parse input, format: 'bibtex'

File.write('bib.txt', bib.to_s)
```

**Comment by SkepticMystic** [comment]
Thank you! This is exactly what I need.
So, in general, one can add options to a command using a comma separated `key: value` pair?

**Comment by SkepticMystic** [comment]
Sorry, another question. I tried to convert it to CSL Json, but `format: 'json'` throws an error.
And the default format is invalid (Green normal Zotero CSL Json out, Red is AnyStyle output):
![image](https://user-images.githubusercontent.com/70717676/132653843-920701a3-a947-4dfc-ade3-a69f2dae9483.png)

**Comment by SkepticMystic** [comment]
I'm gonna ping you because I don't know if you'll get a notification from a closed issue @inukshuk

**Comment by inukshuk** [comment]
Careful, the `json` format is not CSL-JSON, use `csl` for that one. In both cases you will Ruby Hashes in return; they are very similar to JavaScript objects so that's what we use. Actual JSON is a JavaScript object literal as a string -- that's not very useful in Ruby code, that's the API returns a Hash instead. You can call `.to_json` on the Hash to get a realy JSON string.
