### ISSUE TITLE
French word Issue

### ISSUE THREAD

**Issue by sathishvelu2020** [inukshuk/anystyle#181]
"Disponible sur" means "available on"
but anystyler tags it as location 

Plüss-Sugrgeard C, Pegggrisa D, Friedli O, Kronggenerg A. Antibacterial Prescridgegebing in the Outehehpatient Setting: Results from a Longitudinal Study and a Sentinel Network of Physicians, Switzerland. Disponible sur : www.anresis.ch/wp-content/uploads/2566020/09/ABUse_ougggrgetpatient_Pluess_Geneva_2020.pdf

**Comment by inukshuk** [comment]
Thanks! Do you have two or three more references? We can add them to the core training set.

**Comment by sathishvelu2020** [comment]
> Thanks! Do you have two or three more references? We can add them to the core training set.

Sure, i will edit the previous message with the references

**Comment by inukshuk** [comment]
I think it's probably good already with just that one. Give it a try!
