### ISSUE TITLE
One word got lost in the title

### ISSUE THREAD

**Issue by dioubernardo** [inukshuk/anystyle#183]
In this PDF https://iase-web.org/documents/papers/icots5/Topic1m.pdf

![image](https://user-images.githubusercontent.com/3487994/172229259-a814ff2a-7f13-4d63-bf9c-251e44c74638.png)

**Comment by inukshuk** [comment]
That's because there's a missing space in the input. The parser splits tokens on spaces, so the 'The' is part of date segment (and dropped during normalisation).
