### ISSUE TITLE
Possible license issue with `language_detector` dependency

### ISSUE THREAD

**Issue by LiberalArtist** [inukshuk/anystyle#186]
I've been working on packaging AnyStyle for [Guix](https://guix.gnu.org) (a user-mode package manager and GNU/Linux distribution). Like many distributions, Guix has rigorous standards for licensing of packages it distributes. While working through AnyStyle's dependencies, I found that `language_detector` (https://github.com/feedbackmine/language_detector) doesn't actually seem to say what its license is anywhere that I can see.

This is quite regrettable. It sertainly seems like the author intended to release it as open-source software; however, without an actual statement somewhere like "I give you permission to use this software under X terms", the default rule of copyright is that nothing is permitted. Without a license, Guix can't distribute `language_detector`, and presumably the same would be true of Debian, Fedora, and others with careful standards for licensing.

Fortunately, the impact is fairly low, since `language_detector` is a purely optional dependency (thanks to https://github.com/inukshuk/anystyle/commit/53501395e70468559e76b91f52500a76b0cf7961), so I've been able to build AnyStyle and run the test suite without it. Still, it seemed worth raising the issue.

Maybe someone can find a statement of the license for `language_detector` somewhere that I haven't seen? I know there's a fork at https://github.com/igrigorik/language_detector that's also [on RubyGems](https://rubygems.org/gems/language_detector), but I didn't find any more clarity there, either.

Alternatively, maybe it would work to use a different library for language detection? It's not an area I've ever looked into, but I did see `cld` mentioned in:

https://github.com/inukshuk/anystyle/blob/50f1dd547d28ab4b830e45d70e840cb1898a37b0/README.md?plain=1#L117-L119

**Comment by inukshuk** [comment]
Agreed. I've been meaning to replace the language detector with something else for a while, but every time I looked (briefly, admittedly) I didn't find anything I liked or worked particularly well.
