### ISSUE TITLE
Finder & parser gold from the EXcite project

### ISSUE THREAD

**Issue by cboulanger** [inukshuk/anystyle#190]
Hi, I have translated (hopefully correctly) the [gold standard annotations from the EXcite project](https://github.com/exciteproject/EXgoldstandard) to the anystyle format: 

https://github.com/cboulanger/excite-docker/tree/main/Dataset/default/anystyle

It contains manually annotated references from 200+ German and English social science open source articles. Please review and add it if you find it useful. I can also fix bugs the [tranlation algorithm](https://github.com/cboulanger/excite-docker/blob/main/commands/dataset.py) should there be any problems in the output.

**Comment by inukshuk** [comment]
Nice! We can add them everything that gets parsed without errors to the gold set and review any references that produce errors for addition to the core set.

**Comment by cboulanger** [comment]
I have further cleaned up and fixed the excite goldstandard based and put it into a gist for your convenience:

https://gist.github.com/cboulanger/517a209ab30f61c74105e76699d03c24

I will keep updating it when I find more annotation bugs.

**Comment by cboulanger** [comment]
Superseded by #191
