### ISSUE TITLE
pdftotext not found

### ISSUE THREAD

**Issue by Pocoyo7798** [inukshuk/anystyle#209]
Hello, 
I installed the Anystyle, but when I try to run it by: anystyle -f json find 1.pdf, I get this error:
sh: 1: pdftotext: not found
Error processing `1.pdf'
  pdftotext failed with error code 127
  /var/lib/gems/2.7.0/gems/anystyle-1.4.1/lib/anystyle/utils.rb:67:in `pdf_to_text'
  /var/lib/gems/2.7.0/gems/anystyle-1.4.1/lib/anystyle/document.rb:30:in `open'
  ...

My Installation:
NAME
    anystyle - Finds and parses bibliographic references

SYNOPSIS
    anystyle [global options] command [command options] [arguments...]

VERSION
    1.4.1 (cli 1.4.5, data 1.3.0)

GLOBAL OPTIONS
    -F, --finder-model=file - Set the finder model file (default: none)
    -P, --parser-model=file - Set the parser model file (default: none)
    --adapter=name          - Set the dictionary adapter (default: ruby)
    -f, --format=name       - Set the output format (default: ["json"])
    --help                  - Show this message
    --pdfinfo=path          - Set the path for pdfinfo (default: none)
    --pdftotext=path        - Set the path for pdftotext (default: none)
    --[no-]stdout           - Print results directly to stdout
    --[no-]verbose          - Print status messages to stderr
    --version               - Display the program version
    -w, --[no-]overwrite    - Allow overwriting existing files

COMMANDS
    check   - Check tagged documents or references
    find    - Find and extract references from text documents
    help    - Shows a list of commands or help for one command
    license - Print license information
    parse   - Parse and convert references
    train   - Create a new finder or parser model

Thanks for your atention

**Comment by inukshuk** [comment]
To use the finder module with PDF input the [pdftotext](https://en.wikipedia.org/wiki/Pdftotext) binary must also be installed. Depending on your platform there are different ways to install it.

**Comment by Pocoyo7798** [comment]
Oh ok, is the pdftotext from poppler units. It is already solved, thanks for your help!
