### ISSUE TITLE
Minimal amount of data for finder/parser model training?

### ISSUE THREAD

**Issue by Mkranj** [inukshuk/anystyle#213]
Hi, I'm looking to train a new model on own data. From what I understood, the core parser model is trained on 1000 citations, is that right?
How about the finder model? I know not all documents are in the repo as .ttx files, which amount would be recommended for training a new finder model?

Thank you for the hard work.

**Comment by inukshuk** [comment]
I think this is very much a factor of the variety of your data. For the parser model, I'd guess that a model trained on about 50 references should already by OK in many cases. For a long time our default model was trained on less than 500 and with 500-1500 I've experiences the best results myself.

For the finder model we have 15 ttx files in the repo; the default model is trained on an additional 40 files (including books and dissertations with multiple chapters).

**Comment by Mkranj** [comment]
Thank you very much, that's a lot of help :)
