### ISSUE TITLE
Input count wrong:  limit yourself to 1000 references per request

### ISSUE THREAD

**Issue by alan-kerr** [inukshuk/anystyle#216]
Tried to parse 352 references (from a thesis), but the parser said "Be kind! That's quite a lot of input. Since this is a free service, we'd ask you to limit yourself to 1000 references per request." and the parse button is greyed out. 
Input is one reference per line. So only 352 lines. Is there a byte count maybe? 
Any ideas?

**Comment by inukshuk** [comment]
Oh, true, it looks like [it's testing the string length](https://github.com/inukshuk/anystyle.io/blob/master/app/controllers/anystyle_controller.rb#L13)!

**Comment by alan-kerr** [comment]
OK, that makes sense. I guess I need to do it in chunks or run it locally then?

**Comment by inukshuk** [comment]
We'll update the limit eventually but I can't make any promises when I'll find the time. So yes, for the time being you'll have to make the chunks smaller or use the CLI tool locally.

**Comment by alan-kerr** [comment]
OK, thanks!
