### ISSUE TITLE
Consider normalizing whitespace

### ISSUE THREAD

**Issue by paulzzy** [inukshuk/anystyle#218]
When I was copy-pasting a list of citations, I noticed there were a lot of narrow no-break spaces ([U+202F](https://symbl.cc/en/202F/)) which confused the tokenizer (e.g. a `STEM (pp.` token instead of two separate `STEM` and `(pp.` tokens). Would it make sense to normalize whitespace by e.g. replacing all whitespace-like characters with a space?

**Comment by inukshuk** [comment]
You can configure the [parser's `delimiter` option](https://github.com/inukshuk/anystyle/blob/main/lib/anystyle/parser.rb#L108) and add any additional token delimiters.

It would probably be fine to add `\p{Zs}` to the default value which would also cover your case.

**Comment by paulzzy** [comment]
Thanks! Is there a way to change this for the website? I can make a PR for that; otherwise I'll close since this can be fixed through config.

**Comment by inukshuk** [comment]
You're welcome to make a PR here. I'll try to update the anystyle.io over the winter break.
