### ISSUE TITLE
Reference not parsing for this Chinese Character 著

### ISSUE THREAD

**Issue by shalinie22** [inukshuk/anystyle#223]
Getting an error, if I try to parse the below reference in the anystyle.io site because of the Chinese character "著".

Deng, R., and X.L. Zhu. 2020. “A Guandi Devotee’s Journey: Alex HOW-CHOONG, a Prominent Chinese (Hakka) Entrepreneur in Réunion 一个关帝信仰者的奋斗史：记留尼汪著名的华裔（客属）企业家侯沐凯.” <i>Hakka Cultural Heritage Vision 客家文博</i> (3): 60–64.

![image](https://github.com/inukshuk/anystyle/assets/60962646/70648b23-bb5e-4173-a33f-192a4e0d06aa)

**Comment by inukshuk** [comment]
Thanks for reporting! That's odd, I checked the logs and it appears that there's an error in the Wapiti library failing to tokenize this character. We'll have to figure it out there.
