### ISSUE TITLE
wapiti compilation on Windoze?

### ISSUE THREAD

**Issue by chondrops** [inukshuk/anystyle#27]
Hi there,
This tool looks absolutely great for some use-cases I have. But I can't get Wapiti compiled on a couple of Windows boxes I have tried it on. Same error in both cases, using Ruby1.9.3 and the appropriate DevKit.

Can I just double-check that this gem is compatible with Windows platform?

Cheers,
Chondrops.

---
##    Errlog:

generating native-i386-mingw32.def
compiling bcd.c
compiling decoder.c
In file included from decoder.c:43:0:
thread.h:32:21: fatal error: pthread.h: No such file or directory

**Comment by inukshuk** [comment]
I have not used this on Windows yet, but I would be surprised if it were not compatible.

On the other hand, I've had a user report an issue compiling on Windows in the past, but IIRC that was an issue with `sys/time.h` not POSIX threads.

Can you compile other Gems with native extensions?

**Comment by chondrops** [comment]
Yes, no problem compiling other Gems such as unicode-0.4.4.2-x86-mingw32 and json-1.8.2.

Although I note that kyotocabinet also crashes and burns during compilation.

TIA

**Comment by inukshuk** [comment]
I'm not sure whether or not kyoto cabinet is still maintained, so as far as the parser is concerned I'd recommend using Redis instead.

I'm afraid I can't help you much further right now... Can you verify that pthread.h is present in your enviroonment? (Obviously the Compiler does not find it)

**Comment by chondrops** [comment]
Hi there,
No, pthread.h doesn't exist on my system.

I've tracked down a Windows implementation of pthreads, but being rather new to Ruby and Gem compilation, can you perhaps suggest a place to put the header file so it is picked up?

Sorry if this is a very noob question - every location I've tried so far seems to make no difference to compilation failure.

TIA,
chondrops

**Comment by chondrops** [comment]
Scrap that request - I've solved the problem with pthread.h.

But now compilation of native.c dies with:

c:/Ruby193/include/ruby-1.9.1/ruby/win32.h:283:12: error: conflicting types for 'gettimeofday'

So I guess the source needs to be tweaked to get this to compile on Windows. I'll try to get hold of a Linux machine instead of labouring on with Windows.

chondrops.

**Comment by jocelynpender** [comment]
I can confirm that wapiti compilation fails on Windows with conflicting types for 'gettimeofday'
I tried this yesterday, received the same error as detailed above.

**Comment by christoberaps** [comment]
Here the error I am also getting while trying to install wapiti gem:


C:\DevKit>gem install wapiti
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing wapiti:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby193/lib/ruby/gems/1.9.1/gems/wapiti-0.1.1/ext/wapiti
C:/Ruby193/bin/ruby.exe -r ./siteconf20160708-7068-1k5l9gy.rb extconf.rb
checking for main() in -lpthread... no
checking for main() in -lm... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby193/lib/ruby/gems/1.9.1/extensions/x86-mingw32/1.9.1/wapiti-0.1.1/mkmf.log

current directory: C:/Ruby193/lib/ruby/gems/1.9.1/gems/wapiti-0.1.1/ext/wapiti
make  clean

current directory: C:/Ruby193/lib/ruby/gems/1.9.1/gems/wapiti-0.1.1/ext/wapiti
make
generating native-i386-mingw32.def
compiling bcd.c
compiling decoder.c
In file included from decoder.c:43:0:
thread.h:32:21: fatal error: pthread.h: No such file or directory
compilation terminated.
make: *** [decoder.o] Error 1

make failed, exit code 2

Gem files will remain installed in C:/Ruby193/lib/ruby/gems/1.9.1/gems/wapiti-0.1.1 for inspection.
Results logged to C:/Ruby193/lib/ruby/gems/1.9.1/extensions/x86-mingw32/1.9.1/wapiti-0.1.1/gem_make.out

C:\DevKit>

**Comment by WouterJeuris** [comment]
We've come to a working solution for Windows here: https://github.com/inukshuk/wapiti-ruby/issues/3
