### ISSUE TITLE
Citation key for bibtex generated incorrectly when there is an accent in the author's name

### ISSUE THREAD

**Issue by danielsimeone** [inukshuk/anystyle#34]
Input: Lévesque, Andrée. Red Travellers: Jeanne Corbin &amp; Her Comrades (Montreal: McGill-Queen’s University Press, 2006).

Output in BibTeX (I may have corrected the parsing):
@book{l2006a,
  author = {Lévesque, Andrée},
  title = {Red Travellers: Jeanne Corbin &amp; Her Comrades},
  publisher = {McGill-Queen’s University Press},
  date = {2006},
  language = {en},
  address = {Montreal}
}

Citation key is l2006a, expected is lévesque2006a OR levesque2006a, if BibTeX can't handle accents there.

Cheers,
Daniel

**Comment by danielsimeone** [comment]
Same think happened with last name: O’Donnell, where the apostrophe was a French apostrophe. (different character)

**Comment by inukshuk** [comment]
Transliteration of the keys was already implemented, but it seems we forgot to enable it on anystyle.io -- we'll fix it in the next release. Thanks for reporting!
