### ISSUE TITLE
Model data got replaced in training even after setting "false" as second parameter

### ISSUE THREAD

**Issue by vijaynaidu** [inukshuk/anystyle#62]
@inukshuk Impressive work by the tool. I've played around. 
As, i'm new to ruby i can't able to debug. Can you help me on the issue. Please view below for the issue recorded.

![output](https://user-images.githubusercontent.com/10484307/26925714-7cde988c-4c68-11e7-8c03-5bb4febb8207.gif)

**Comment by inukshuk** [comment]
Yes, there is a longstanding issue with incremental training that I haven't had the time to get to the bottom of (also see [this comment](https://github.com/inukshuk/anystyle-parser/issues/40#issuecomment-167536807) for more details).

Basically, you can work around this by keeping your training data and always training the model with the whole data set. This won't scale for large training data sets and makes the training process last longer, but that shouldn't be a problem in most scenarios. In my experience, you get very good results with curated training data set of about 50-400 references (depending on how much variance in styles and languages there is in your data).

**Comment by vijaynaidu** [comment]
@inukshuk  Thanks for your help
