### ISSUE TITLE
Intalling anystyle on Windows 10

### ISSUE THREAD

**Issue by njumarlon** [inukshuk/anystyle#75]
Hi!

I tried to install anystyle parser on Windows 10 (64bit) with Ruby 1.9.3p0 [i386-mingw32]. But I got the errors below:

C:\DevKit>gem install anystyle-parser
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing anystyle-parser:
        ERROR: Failed to build gem native extension.

        C:/Ruby193/bin/ruby.exe extconf.rb
checking for main() in -lpthread... no
checking for main() in -lm... yes
creating Makefile

make
generating native-i386-mingw32.def
compiling bcd.c
compiling decoder.c
In file included from decoder.c:43:0:
thread.h:32:21: fatal error: pthread.h: No such file or directory
compilation terminated.
make: *** [decoder.o] Error 1

Gem files will remain installed in C:/Ruby193/lib/ruby/gems/1.9.1/gems/wapiti-0.1.1 for inspection.
Results logged to C:/Ruby193/lib/ruby/gems/1.9.1/gems/wapiti-0.1.1/ext/wapiti/gem_make.out

I tried to solve this problem by searching answers from the web but couldn't find a solution. Can anyone help? Thank you a lot! This has puzzled me quite a while.

**Comment by WouterJeuris** [comment]
We've come to a working solution for Windows here: https://github.com/inukshuk/wapiti-ruby/issues/3
