### ISSUE TITLE
Using anystyle-parser withour gem installtion

### ISSUE THREAD

**Issue by dominic-sps** [inukshuk/anystyle#84]
Is it possible to use anystyle-parser without installing it as a gem. Noted that there are few code activity in the recent days and wondering what has been changed. Is there a sample to try this source directly.

**Comment by inukshuk** [comment]
Yes, of course you can use the latest version on master directly by either cloning this repository. However, I would advise you to wait a little longer: there are a number of changes planned to make the parser better and easier to use in the coming weeks.

**Comment by dominic-sps** [comment]
Sure. Thank you for your response. In the mean time, if you have few test samples, it would be of great help. I am not a ruby developer and hence I find it difficult to try out few things.

**Comment by dominic01** [comment]
Just wondering how is it possible  to run it without installing the gem.
