### ISSUE TITLE
Add  a 'Series' tag

### ISSUE THREAD

**Issue by lenrsmith** [inukshuk/anystyle#99]
First, I love Anystyle! You just saved hours from my current project. 

Second, a `Series` tag would be great. I have a lot of entries where `title` and `booktitle` are not enough as the book is part of a larger series. In `biblatex`.  For instance, 

```Deeley, Mary Katharine. “Ezekiel’s Shepherd and John’s Jesus.” In Early Christian Interpretation of the Scriptures of Israel: Investigations and Proposals, edited by Craig A. Evans and James A. Sanders, 252–264. Journal for the Study of the New Testament Supplement Series 148. Sheffield, England: Sheffield Academic Press, 1997.```

This entry is an article in a book that is in a series: 

```title = “Ezekiel’s Shepherd and John’s Jesus.”
booktitle = Early Christian Interpretation of the Scriptures of Israel: Investigations and Proposals
series = Journal for the Study of the New Testament Supplement Series
volume = 148
```

I can work around the issue for now, but I don't want to *teach* the system bad habits.

**Comment by inukshuk** [comment]
We're just putting the finishing touches on a rewrite of the parser engine and, whilst we cut down on the number of segment tags in general, you're absolutely right that we were missing a tag for this. It is called `collection-title` in the new version (but it's not clear when we'll migrate the changes to the web site).

**Comment by lenrsmith** [comment]
Awesome! Thanks for making this tool available.


---------------------------------------------------
Leonard Smith
lenrsmith@gmail.com
